### ISSUE TITLE
Wrong Stats or Stats not availablle

### ISSUE THREAD

**Issue by fricoben** [lfglabs-dev/stats.starknet.id#31]
- Renew graph is not working (it's not the right renewal stats)

<img width="515" alt="Capture d’écran 2023-11-03 à 17 39 40" src="https://github.com/starknet-id/stats.starknet.id/assets/78437165/5003680d-9b96-4431-82d1-505fac20c1c7">

- Clubs stats don't work

<img width="1073" alt="Capture d’écran 2023-11-03 à 17 39 47" src="https://github.com/starknet-id/stats.starknet.id/assets/78437165/f804aae8-1b88-4aa9-8c78-792d255519fd">

- Other queries are also showing false data because we have many more identities than domains and same for unique address

<img width="1106" alt="Capture d’écran 2023-11-03 à 17 43 47" src="https://github.com/starknet-id/stats.starknet.id/assets/78437165/a80b3eac-e93b-4479-b798-6f9fc287d8f3">

**Comment by lauchaves** [comment]
Hey @fricoben may I give this one a try!? Would love to give a hand!
